from . import res_partner
from . import res_users
from . import res_partner_tax
from . import res_partner_class
from . import related_company
from . import sale_order
from . import sale_order_line
from . import sale_order_report
from . import sale_order_wf_delivery
from . import product_template
from . import idx_ecommerce_warehouse
from . import stock_lot
from . import stock_quant
from . import idx_sale_order_ocr1
from . import idx_sale_order_ocr2
from . import loyalty_program
from . import loyalty_card
from . import crm_lead
from . import loyalty_program_code
from . import survey_survey
from . import account_statement
from . import res_config_setting
from . import idx_business_category
from . import idx_product_category
from . import website
from . import idx_test_requisition1
from . import idx_test_requisition2
from . import survey_user_input
from . import available_download
from . import report_batch_download
