{
    "name": "idx商務管理平台",
    "summary": "商務管理功能",
    "description": "商務管理功能",
    "author": "IDX",
    "category": "Services/Project",
    "version": "1.0",
    "depends": [
        "mail",
        "base",
        "sale_management",
        "website_sale",
        "website_sale_stock",
        "website_sale_loyalty",
        "stock",
        "crm",
        "product_expiry",
        "idx_wf_sync",
        "queue_job",
        "loyalty",
        "survey",
        "portal",
        "bus",
    ],
    "external_dependencies": {
        "python": ["pycryptodome", "qrcode", "Pillow", "XlsxWriter", "openpyxl"],
    },
    "data": [
        "data/crm_category.xml",
        "data/res_partner_category.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/ir_cron_data.xml",
        "data/skin_symptom_data.xml",
        "data/product_category_data.xml",
        "data/uom_category_data.xml",
        "data/product_template_data.xml",
        "data/survey_survey_data.xml",
        "data/available_download_data.xml",
        "wizards/loyalty_generate_wizard.xml",
        "wizards/idx_wf_sync_wizard.xml",
        "wizards/idx_merge_order_wizard.xml",
        "wizards/sync_onedrive.xml",
        "wizards/pricelist_wf_sync_wizard.xml",
        "wizards/idx_replenish_consumable_quantity_wizard.xml",
        "views/back/idx_product_category.xml",
        "views/back/survey_survey.xml",
        "views/front/templates.xml",
        "views/front/portal_templates.xml",
        "views/front/idx_qrcode_portal.xml",
        "views/back/product_template.xml",
        "views/back/stock_lot.xml",
        "views/back/stock_quant.xml",
        "views/back/idx_ecommerce_warehouse.xml",
        "views/back/res_partner.xml",
        "views/back/res_partner_tax.xml",
        "views/back/res_partner_class.xml",
        "views/back/related_company.xml",
        "views/back/sale_order.xml",
        "views/back/idx_sale_order_ocr1.xml",
        "views/back/idx_sale_order_ocr2.xml",
        "views/back/idx_test_requisition1.xml",
        "views/back/idx_test_requisition2.xml",
        "views/back/crm_lead.xml",
        "views/back/account_statement.xml",
        "views/back/loyalty_card.xml",
        "views/back/loyalty_program.xml",
        "views/back/loyalty_program_code.xml",
        "views/back/res_config_setting.xml",
        "views/back/idx_business_category.xml",
        "views/back/website_sale_loyalty_menus.xml",
        "views/back/website_sale_menus.xml",
        "views/back/sale_menus.xml",
        "views/back/contact_views.xml",
        "views/back/crm_menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "idx_ebs/static/src/js/loyalty_card_list_view.js",
            "idx_ebs/static/src/xml/empty_loyalty_buttons.xml",
            "idx_ebs/static/src/js/idx_ocr_page.js",
            "idx_ebs/static/src/views/idx_ocr_page1.xml",
            "idx_ebs/static/src/views/idx_ocr_page2.xml",
            "idx_ebs/static/src/xml/ocr_buttons.xml",
            "idx_ebs/static/src/js/wf_b2b_buttons.js",
            "idx_ebs/static/src/xml/wf_b2b_buttons.xml",
            "idx_ebs/static/src/js/merge_orders.js",
            "idx_ebs/static/src/views/sync_onedrive_buttons.xml",
            "idx_ebs/static/src/css/idx_ocr_page.css",
        ],
        "web.assets_frontend": [
            "idx_ebs/static/src/xml/cart_notification.xml",
            "idx_ebs/static/src/scss/templates.scss",
            "idx_ebs/static/src/scss/cart_filter.scss",
            "idx_ebs/static/src/js/detects_widget_view.js",
            "idx_ebs/static/src/js/detects_widget.js",
            "idx_ebs/static/src/js/cart_filter.js",
            "idx_ebs/static/src/js/cart_detects_btn.js",
            "idx_ebs/static/src/js/report_download.js",
            "idx_ebs/static/src/js/batch_download_bus.js",
            "idx_ebs/static/src/js/pic_upload.js",
            "idx_ebs/static/src/js/carrier_save.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
